
target 'Segment-Firebase_Example' do
  use_frameworks!
  pod 'Segment-Firebase', :path => '../'

end

target 'Segment-Firebase_Tests' do
  use_frameworks!

  # pod 'Segment-Firebase', :path => '../'
  pod 'Analytics', '~> 3.2'
  pod 'Firebase/Analytics', '~> 3.3'

  pod 'Quick' # runner lib
  pod 'Nimble' # Matcher lib
  pod 'Mockingjay' # Http mocking
end
